import { CreateDomain } from "../models/models";

export const CREATE_INGESTION_CONTROLS: CreateDomain[] = [
    {
        "header": "Basic Details",
        "data": [
            {
                "name": "Requestor Name",
                "type": "searchable-dropdown",
                "isReq": true,
                "value": null,
                "key": "requesterName",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "Search name or mudid or email",
                "reference_data_type":"requester_name",
                "data": []
            },
            {
                "name": "Dataset Name",
                "type": "textarea",
                "isReq": true,
                "value": null,
                "key": "datasetName",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "Type Here"
            },
            {
                "name": "Dataset SME",
                "type": "searchable-dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "datasetSmeName",
                "valmsg": "custom msg",
                "placeHolder": "Search name or mudid or email",
                "reference_data_type":"dataset_sme_name",
                "data": []
            },
            {
                "name": "Rationale for this request, including what it will help you achieve and/or its important",
                "type": "textarea",
                "isReq": true,
                "value": null,
                "key": "requestRationaleReason",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "-"
            },
            {
                "name": "Dataset originating source name",
                "type": "textarea",
                "isReq": true,
                "value": null,
                "key": "datasetOriginSource",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "--"
            },
            {
                "name": "Current data location",
                "type": "radio",
                "isReq": false,
                "value": null,
                "key": "currentDataLocationRef",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "",
                "reference_data_type":"current_data_location_ef",
                "data":[]
            },
            {
                "name": "Please provide a URL or path where this data is located",
                "type": "input",
                "isReq": false,
                "value": null,
                "key": "dataLocationPath",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "-"
            },
            {
                "name": "Will Meteor / SPACE / Domino be used for data analysis?",
                "type": "radio",
                "isReq": true,
                "value": null,
                "key": "meteorSpaceDominoUsageFlag",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "",
                "reference_data_type":"meteor_space_domino_usage_flag",
                "data":[]
            },
            {
                "name": "Does the data contain Individual Human Data?",
                "type": "radio",
                "isReq": true,
                "value": null,
                "key": "ihdFlag",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "",
                "reference_data_type":"ihd_flag",
                "data":[]
            },
            {
                "name": "Is the data set required for exploration or industrialization?",
                "type": "radio",
                "isReq": true,
                "value": null,
                "key": "datasetRequiredForRef",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "",
                "reference_data_type":"dataset_required_for_ref",
                "data":[]
            },
        ]
    },
    {
        "header": "Prioritization details",
        "data": [
            {
                "name": "What is the estimated data set size / volume?",
                "type": "dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "estimatedDataVolumeRef",
                "valmsg": "custom msg",
                "placeHolder": "Select here",
                "reference_data_type":"estimated_data_volume_ref",
                "data": []
            },
            {
                "name": "What is the expected frequency of refresh for the data?",
                "type": "dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "dataRefreshFrequency",
                "valmsg": "custom msg",
                "placeHolder": "Select here",
                "reference_data_type":"data_refresh_frequency",
                "data": []
            },
            {
                "name": "When is the analysis of the data set expected to be initiated?",
                "type": "date",
                "isReq": true,
                "value": null,
                "key": "analysisInitDt",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "---"
            },
            {
                "name": "When is the analysis of the data set expected to be completed?",
                "type": "date",
                "isReq": true,
                "value": null,
                "key": "analysisEndDt",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "---"
            },
            {
                "name": "Is the contract / DTA (Data Transfer Agreement) complete?",
                "type": "radio",
                "isReq": true,
                "value": null,
                "key": "dtaContractCompleteFlag",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "",
                "reference_data_type":"dta_contract_complete_flag",
                "data":[]
            },
            {
                "name": "What is the expected date for contract / DTA to be in place?",
                "type": "date",
                "isReq": true,
                "value": null,
                "key": "dtaExpectedCompletionDate",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "---"
            },
        ]
    },
    {
        "header": "Dataset details",
        "data": [
            {
                "name": "Data category",
                "type": "dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "dataCategoryRefs",
                "valmsg": "custom msg",
                "placeHolder": "Select here",
                "reference_data_type":"data_category_refs",
                "multi": true,
                "data": []
            },
            {
                "name": "Dataset Type",
                "type": "radio",
                "isReq": true,
                "value": null,
                "key": "datasetTypeRef",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "",
                "reference_data_type":"data_source_type",
                "data":[]
            },
            {
                "name": "Study_ID",
                "type": "dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "studyIds",
                "valmsg": "custom msg",
                "placeHolder": "--",
                "multi": true,
                "reference_data_type":"study_ids",
                "data": []
            },
            {
                "name": "Data Owner",
                "type": "searchable-dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "datasetOwnerName",
                "valmsg": "custom msg",
                "placeHolder": "Search name or mudid or email",
                "reference_data_type":"dataset_owner_name",
                "data": []
            },
            {
                "name": "Data Steward",
                "type": "searchable-dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "datasetStewardName",
                "valmsg": "custom msg",
                "placeHolder": "Search name or mudid or email",
                "reference_data_type":"dataset_steward_name",
                "data": []
            },
            {
                "name": "Contract Partner",
                "type": "input",
                "isReq": true,
                "value": null,
                "key": "contractPartner",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "--"
            },
            {
                "name": "Retension rules",
                "type": "retension-rules-dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "retentionRules",
                "valmsg": "custom msg",
                "placeHolder": "Not applicable",
                "reference_data_type":"retention_rules",
                "data": []
            },
            {
                "name": "Usage Restrictions(select all that apply)",
                "type": "dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "usageRestrictions",
                "valmsg": "custom msg",
                "placeHolder": "Not applicable",
                "multi": true,
                "reference_data_type":"usage_restrictions",
                "data": []
            },
            {
                "name": "User Restrictions(select all that apply)",
                "type": "dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "userRestrictions",
                "valmsg": "custom msg",
                "placeHolder": "Not applicable",
                "multi": true,
                "reference_data_type":"user_restrictions",
                "data": []
            },
            {
                "name": "Information Classification Type",
                "type": "dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "informationClassificationTypeRef",
                "valmsg": "custom msg",
                "placeHolder": "Select here",
                "multi": false,
                "reference_data_type":"information_classification_type",
                "data": []
            },
            {
                "name": "PII Type",
                "type": "dropdown",
                "isReq": true,
                "isDynamic": false,
                "tooltip": true,
                "value": null,
                "key": "piiTypeRef",
                "valmsg": "custom msg",
                "placeHolder": "Select here",
                "multi": false,
                "reference_data_type":"pii_type",
                "data": []
            },
            {
                "name": "Therapy Area",
                "type": "searchable-dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "therapyAreas",
                "valmsg": "custom msg",
                "placeHolder": "Search and Select",
                "multi": true,
                "reference_data_type":"therapy_areas",
                "data": []
            },
            {
                "name": "Technique and assay",
                "type": "searchable-dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "techniqueAndAssays",
                "valmsg": "custom msg",
                "placeHolder": "Search and Select",
                "multi": true,
                "reference_data_type":"technique_and_assays",
                "data": []
            },
            {
                "name": "Indication",
                "type": "searchable-dropdown",
                "isReq": false,
                "isDynamic": false,
                "tooltip": false,
                "value": null,
                "key": "indications",
                "valmsg": "custom msg",
                "placeHolder": "Search and Select",
                "multi": true,
                "reference_data_type":"indications",
                "data": []
            },
        ]
    },
    {
        "header": "Technical details",
        "data": [
            {
                "name": "Targeted ingestion start date",
                "type": "date",
                "isReq": false,
                "value": null,
                "key": "targetIngestionStartDate",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "---"
            },
            {
                "name": "Targeted ingestion end date (Applicable only if data refresh frequency is not one-time refresh)",
                "type": "date",
                "isReq": false,
                "value": null,
                "key": "targetIngestionEndDate",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "---"
            },
            {
                "name": "Target path",
                "type": "input",
                "isReq": false,
                "value": null,
                "key": "targetPath",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "---"
            },
            {
                "name": "Dataset Type ingestion",
                "type": "radio",
                "isReq": false,
                "value": null,
                "key": "datasetTypeIngestionRef",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "",
                "reference_data_type":"dataset_type_ingestionR_ref",
                "data":[]
            },
            {
                "name": "Email addresses for guest user(s) from third party organization",
                "type": "input",
                "isReq": false,
                "value": null,
                "key": "guestUsersEmail",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "Type Email ID's as comman separated values (Ex: john@xyz.com, jane@xyz.com)"
            },
            {
                "name": "IP addresses that need to be whitelisted",
                "type": "textarea",
                "isReq": false,
                "value": null,
                "key": "whitelistIpAddresses",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "Type IP addresses as comma separated values (Ex: 168.98.22.1, 168.98.22.3)"
            },
            {
                "name": "External staging container name",
                "type": "input",
                "isReq": false,
                "value": null,
                "key": "externalStagingContainerName",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "Type here"
            },
            {
                "name": "External source location",
                "type": "input",
                "isReq": false,
                "value": null,
                "key": "externalDataSourceLocation",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "Type here"
            },
            {
                "name": "How can XYZ access the source location?",
                "type": "dropdown",
                "isReq": false,
                "value": null,
                "key": "gskAccessSourceLocationRef",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": false,
                "placeHolder": "Select here",
                "reference_data_type":"gsk_access_source_location_ref",
                "data": []
            },
            {
                "name": "Secret key name of external data source user",
                "type": "input",
                "isReq": false,
                "value": null,
                "key": "externalSourceSecretKeyName",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "Type here"
            },
            {
                "name": "Select Source Domain",
                "type": "dropdown",
                "isReq": false,
                "value": null,
                "key": "domainRequestId",
                "valmsg": "custom msg",
                "isDynamic": false,
                "tooltip": true,
                "placeHolder": "Select",
                "reference_data_type":"domain_type",
                "data": []
            },
        ]
    }
]
